version: '3'
services:
    pwn:
        container_name: pwn_test
        image: qrzbing/pwndocker
        privileged: true
        cap_add:
            - SYS_PTRACE
        ports:
            - "23946:23946"
