version: '3'
services:
    pwn:
        container_name: pwn_test
        image: qrzbing/pwn-docker
        privileged: true
        cap_add:
            - SYS_PTRACE
        ports:
            - "23946:23946"
        # volumes:
        #     - <YOUR_PATH_TO_WORKS>/CTF:/ctf/work/CTF
